'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import PomodoroWidget from "./components/PomodoroWidget";
import { useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabaseBrowser";
import { useRouter, usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata must be exported from a server component, move to a separate file if needed
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout(props: { children: React.ReactNode }) {
  const [renderWidget, setRenderWidget] = useState(false);
  const [user, setUser] = useState<any>(null);
  const router = useRouter();
  const pathname = usePathname();
  
  useEffect(() => {
    // Only render widget after mount to avoid hydration issues
    setRenderWidget(true);
    
    // Check auth status
    const checkUser = async () => {
      const supabase = supabaseBrowser();
      const { data: { session } } = await supabase.auth.getSession();
      setUser(session?.user || null);
    };
    
    checkUser();
    
    // Listen for auth changes
    const supabase = supabaseBrowser();
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user || null);
    });
    
    return () => subscription.unsubscribe();
  }, []);
  
  const handleLogout = async () => {
    const supabase = supabaseBrowser();
    await supabase.auth.signOut();
    // Clear the auth cookie
    document.cookie = 'sb-auth-token=; path=/; max-age=0';
    router.push('/auth/login');
    router.refresh();
  };
  
  const isLoginPage = pathname?.startsWith('/auth/login');
  
  return (
    <html lang="en">
      <body className="min-h-screen">
        <header className="border-b">
          <nav className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
            <div className="flex items-center gap-4">
              <Link href="/" className="text-base font-semibold">
                DayFlow D2
              </Link>
              {user && (
                <Link href="/today" className="text-sm hover:underline">
                  Today
                </Link>
              )}
            </div>
            {user && !isLoginPage && (
              <div className="flex items-center gap-4">
                <span className="text-sm text-gray-600">{user.email}</span>
                <button
                  onClick={handleLogout}
                  className="text-sm text-gray-600 hover:text-gray-900 hover:underline"
                >
                  Logout
                </button>
              </div>
            )}
          </nav>
        </header>

        <main className="mx-auto max-w-5xl px-4 py-6">
          {props.children}
        </main>
        
        {renderWidget && <PomodoroWidget />}
      </body>
    </html>
  );
}